### ISSUE TITLE
Help text does not carry over

### ISSUE THREAD

**Issue by robballou** [sreynen/cincio#5]
Looks like the field "help text" does not work on the node types tab.

The `field_file` has help text defined here:

![screenshot 2015-03-23 10 06 25](https://cloud.githubusercontent.com/assets/46527/6784259/53ba87be-d144-11e4-971f-84102a72e991.png)

But it does not show up in the following:

`field.storage.node.field_file`:

```yaml
id: node.field_file
field_name: field_file
entity_type: node
type: file
cardinality: Unlimited
settings: [ ]
```

`field.node.blog.field_file.yml`:

```yaml
id: node.blog.field_file
label: Files
entity_type: node
bundle: blog
field_type: file
field_name: field_file
settings:
  file_directory: field/blog_files
  file_extensions: pdf, doc, xls, ppt, docx, xlsx, pptx
dependencies:
  entity:
    - field.storage.node.field_file
    - node.type.blog
```
